version: "3.8"

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      DB_HOST: .
      MYSQL_DATABASE: "main"
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "test"
      MYSQL_TCP_PORT: 17001
    ports:
      - "17001:17001"
    volumes:
      - ./MySQLData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17001"]
      interval: 10s
      timeout: 10s
      retries: 10
  api:
    restart: on-failure
    build:
      dockerfile: ./MoneyAPI/Dockerfile
    volumes:
      - type: bind
        source: ./MoneyAPI
        target: /app
    ports:
      - 17002:17002
    depends_on:
      database:
        condition: service_healthy

networks:
  main: