version: "3.8"

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      DB_HOST: .
      MYSQL_DATABASE: "main"
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "test"
      MYSQL_TCP_PORT: 17011
    ports:
      - "17011:17011"
    volumes:
      - ./mySQLData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:17011"]
      interval: 10s
      timeout: 10s
      retries: 10
  users-api:
    build: ./users/Dockerfile
    restart: on-failure
    environment:
      PORT: 17010
      MYSQL_URI: "mysql+pymysql://api:test@database:17011/main"
    volumes:
      - ./users:/app
    ports:
      - "17010:17010"
    depends_on:
      database:
        condition: service_healthy